### ISSUE TITLE
Support for Other Countries

### ISSUE THREAD

**Issue by saamerm** [migueldeicaza/CovidGraphs#28]
In order for other countries to be able to use the app, the backend would need to support those countries.
However, it doesn't seem like many other countries return the data.

If you go to :
https://tirania.org/covid-data/US, https://tirania.org/covid-data/Germany, https://tirania.org/covid-data/Spain, you'll notice that it returns a JSON with data. 
However, other countries like UK, Canada, Australia are missing in the backend, as they all return a blank page:
https://tirania.org/covid-data/Canada, https://tirania.org/covid-data/Australia, https://tirania.org/covid-data/UK

Is there a way we can help add those countries as well?

**Comment by migueldeicaza** [comment]
They are already there, you just need to enter the actual name from the database, which you can see in the file "global"

It is not "UK" but "United Kingdom" for example, and Canada is not one country, but reported as different provinces, same for Australia.

You can see the repo "CovidExtractor" to see how the data is generated, and if you want, you could contribute an aggregator for Canada/Australia.

**Comment by migueldeicaza** [comment]
Apologies, just realized that I did not open the extractor, it is now open (it is 90% shared code anyways)

**Comment by saamerm** [comment]
Ok perfect. Yes I was looking for it.
